Starry/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from twinkle.sitemaps import TwinkleSitemap
from django.contrib.auth.views import login,logout,logout_then_login,password_change,password_change_done
from twinkle import views
sitemaps = {
    'twinkles': TwinkleSitemap,
}
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^twinkle/', include('twinkle.urls',namespace='twinkle',app_name='twinkle')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^login/$',login,name='login'),
    url(r'^logout/$',logout,name='logout'),
    url(r'^logout-then-login/$',logout_then_login,
        name='logout_then_login'),
    url(r'^$',views.dashboard,name='dashboard'),
    url(r'^password-change/$',password_change,name='password_change'),
    url(r'^password-change/done/$',password_change_done,name='password_change_done'),
]

twinkle/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from twinkle import views


urlpatterns = [
    url(r'^$', views.twinkle_list, name='twinkle_list'),
    #url(r'^$', views.PostListView.as_view(), name='twinkle_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/'\
        r'(?P<slug>[-\w]+)/$',
    views.twinkle_detail,name='twinkle_detail'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.twinkle_list,
        name='twinkle_list_by_tag'),

]

twinkle/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')
class Twinkle(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
        unique_for_date='publish')
    author = models.ForeignKey(User,related_name='twinkles_user')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
        choices=STATUS_CHOICES,default='draft')

    objects = models.Manager()
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('twinkle:twinkle_detail',
            args=[self.publish.year,
            self.publish.strftime('%m'),
            self.publish.strftime('%d'),
            self.slug])

twinkle/forms.py
from django import forms
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

twinkle/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from models import Twinkle
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth import authenticate, login
from forms import LoginForm
from django.http import HttpResponse

def twinkle_list(request, tag_slug=None):
    object_list = Twinkle.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        twinkles = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        twinkles = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        twinkles = paginator.page(paginator.num_pages)
    return render(request, 'twinkle/Twinkle/list.html', {'page': page,
                                                   'twinkles': twinkles,
                                                         'tag': tag})


class TwinkleListView(ListView):
    queryset = Twinkle.published.all()
    context_object_name = 'twinkles'
    paginate_by = 5
    template_name = 'twinkle/Twinkle/list.html'

def twinkle_detail(request, year, month, day, slug):
    twinkle = get_object_or_404(Twinkle, slug=slug,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day)
    # List of similar posts
    twinkle_tags_ids = twinkle.tags.values_list('id', flat=True)
    similar_twinkles = Twinkle.published.filter(tags__in=twinkle_tags_ids).exclude(id=twinkle.id)
    similar_twinkles = similar_twinkles.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]
    return render(request,'twinkle/Twinkle/detail.html',{'twinkle': twinkle,
                  'similar_twinkles': similar_twinkles})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
        return render(request, 'twinkle/login/login.html', {'form': form})

from django.contrib.auth.decorators import login_required
@login_required
def dashboard(request):
    return render(request,'twinkle/dashboard.html',{'section': 'dashboard'})

twinkle/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
           <a href="?page={{page.previous_page_number}}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

twinkle/templates/twinkle/Twinkle/detail.html
{% extends "twinkle/base.html" %}

{% block title %}{{ twinkle.title }}{% endblock %}

{% block content %}
    <h1>{{ twinkle.title }}</h1>
    <p class="date">Published {{ twinkle.publish }} by {{ twinkle.author }}</p>
    {{ twinkle.body|linebreaks }}

    <h2>Similar twinkles</h2>
    {% for twinkle in similar_twinkles %}
        <p><a href="{{ twinkle.get_absolute_url }}">{{ twinkle.title }}</a></p>
        {% empty %}
            There are no similar twinkles yet.
    {% endfor %}
{% endblock %}



twinkle/templates/twinkle/Twinkle/latest_twinkles.html
<ul>
	{% for twinkle in latest_twinkles %}
		<li> 
				<a href="{{ twinkle.get_absolute_url }}">{{ twinkle.title }}</a>
		</li>
	{% endfor %}
</ul>

twinkle/templates/twinkle/Twinkle/list.html
{% extends "twinkle/base.html" %}

{% block title  %}My Twinkle{% endblock %}
{% block content %}



  <h1>My Twinkle</h1>
  {% if tag %}
    <h2>Twinkles tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for twinkle in twinkles %}
    <h2>
      <a href="{{ twinkle.get_absolute_url }}">{{ twinkle.title }}</a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in twinkle.tags.all %}
      <a href="{% url 'twinkle:twinkle_list_by_tag' tag.slug %}">
      {{ tag.name }}
      </a>
      {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Published {{ twinkle.publish }} by {{ twinkle.author }}
    </p>
    {{ twinkle.body|truncatewords:30|linebreaks }}
  {% endfor %}
{% include "pagination.html" with page=twinkles %}
{% endblock %}



twinkle/templates/twinkle/base.html
{% load staticfiles %}
{% load twinkle_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/twinkle.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My twinkle</h2>
        <p>This is my twinkle.</p>
        {% show_latest_twinkles 3 %}
    </div>
</body>
</html>

twinkle/templates/twinkle/dashboard.html
{% extends "registration/base.html" %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<h1>Dashboard</h1>
<p>Welcome to your dashboard.</p>
{% endblock %}